apiVersion: v1
kind: Pod
metadata:
  name: jenkins-insights-data-py
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.27-1
    resources:
      requests:
        memory: 0.5Gi
        cpu: "0.1"
      limits:
        memory: 0.5Gi
        cpu: "0.5"
    imagePullPolicy: IfNotPresent
    tty: true
  - name: docker
    image: docker:17.03
    resources:
      requests:
        memory: 0.5Gi
        cpu: "0.1"
      limits:
        memory: 0.5Gi
        cpu: "0.5"
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock
      - name: docker-password
        mountPath: /tmp/docker-password/
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
  - name: docker-password
    secret:
      secretName: docker-password
